### ISSUE TITLE
Support for LPS22DF

### ISSUE THREAD

**Issue by dhir-g** [pilotak/LPS35HW#3]
Can you please add support for LPS22DF sensor?

**Comment by pilotak** [comment]
Try changing the ID to `0x0F`

https://github.com/pilotak/LPS35HW/blob/3d4f8396cc13938beac07dd8a9ba192449e36f22/LPS35HW.h#L35

I don't know if there are any other difference between LPS35HW and LPS22DF, you will need to try

**Comment by dhir-g** [comment]
The control registers are somewhat different in LPS22Df and LPS22HB and that's why I am somwhat skeptical whether changing only the Who Am I reg value will work or not

**Comment by pilotak** [comment]
well in this case i can't help
